name: Run Linter and Tests
on: [pull_request]

jobs:
    build:
        name: Run Linting and Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.7
            - name: Install Poetry
              uses: abatilo/actions-poetry@v2
              with:
                  poetry_version: 1.2.2
            - name: Run Linter
              run: poetry run flake8
            - name: Run Linter
              run: poetry run python -m pytest --cov=src --cov-branch
